apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - image: atlastestapp
        name: testapp
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: testapp
# spec:
#   ports:
#   - port: 5000
#     targetPort: 5000
#   selector:
#     app: testapp
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: degradingapp
# spec:
#   replicas: 1
#   revisionHistoryLimit: 3
#   progressDeadlineSeconds: 15
#   selector:
#     matchLabels:
#       app: degradingapp
#   template:
#     metadata:
#       labels:
#         app: degradingapp
#     spec:
#       restartPolicy: Never
#       containers:
#       - image: atlasdegradingapp
#         name: degradingapp
#         imagePullPolicy: Never
#         ports:
#         - containerPort: 5000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: degradingapp
# spec:
#   ports:
#   - port: 5000
#     targetPort: 5000
#   selector:
#     app: degradingapp
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 15
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
