apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - image: docker.io/1mihirpandya/testapp
        name: testapp
#         imagePullPolicy: Never
        ports:
        - containerPort: 5000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: testapp
# spec:
#   ports:
#   - port: 5000
#     targetPort: 5000
#   selector:
#     app: testapp
# ---
# apiVersion: atlas.demo.com/v1
# kind: DegradingApp
# metadata:
#   name: degradingappexample
# spec:
#   image: degradingapp
#   replicas: 3
